/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.26.0-373-gdf9d0fb33 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.26.0-373-gdf9d0fb33"
#endif
#define SDL_REVISION_NUMBER 0
